In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
df = pd.read_csv('../../data/raw/carsome_data_raw.csv')

In [36]:
df

,Year,Model,Total_Price,Price_per_month,Mileage,Transmission,Location,Highlight,URL
0,2017,Perodua Myvi SE 1.5,"RM\n 35,400",RM 406,"92,189 km",Automatic,"CARSOME Showroom Setia SPICE, Pulau Pinang 14,...",National Daily Drive,https://www.carsome.my/buy-car/perodua/myvi/20...
1,2023,Subaru Forester L EyeSight 2.0,"RM\n 115,800","RM 1,137","14,200 km",Automatic,"CARSOME PJ Automall, Selangor 14,748.1 km\n ...",Compact SUV,https://www.carsome.my/buy-car/subaru/forester...
2,2018,Honda Jazz S i-VTEC 1.5,"RM\n 52,900",RM 611,"75,759 km",Automatic,"CARSOME Showroom Kuala Terengganu, Terengganu ...",Daily Drive,https://www.carsome.my/buy-car/honda/jazz/2018...
3,2016,Mazda CX-3 SKYACTIV 2.0,"RM\n 55,800",RM 711,"59,833 km",Automatic,"CARSOME Showroom Kota Kinabalu, Sabah 13,814.5...",Compact SUV,https://www.carsome.my/buy-car/mazda/cx-3/2016...
4,2021,Perodua Myvi AV 1.5,"RM\n 49,900",RM 460,"69,974 km",Automatic,"CARSOME Showroom Johor Jaya, Johor 14,832.8 km...",National Daily Drive,https://www.carsome.my/buy-car/perodua/myvi/20...
...,...,...,...,...,...,...,...,...,...
1831,2019,Mercedes-Benz A200 Progressive Line 1.3,"RM\n 132,000","RM 1,447","30,014 km",Automatic,"CARSOME Showroom Setiawangsa, Kuala Lumpur 14,...",Luxury,https://www.carsome.my/buy-car/mercedes-benz/a...
1832,2018,Mazda 3 SKYACTIV-G High 2.0,"RM\n 69,000",RM 828,"97,077 km",Automatic,"CARSOME Showroom Kempas, Johor 14,839.0 km\n ...",Upgrade Daily Drive,https://www.carsome.my/buy-car/mazda/3/2018-ma...
1833,2016,Toyota Vios GX 1.5,"RM\n 50,500",RM 686,"144,662 km",Automatic,"CARSOME Showroom Setia SPICE, Pulau Pinang 14,...",Daily Drive,https://www.carsome.my/buy-car/toyota/vios/201...
1834,2022,BMW X3 xDrive30i M Sport 2.0,"RM\n 219,800","RM 2,409","47,126 km",Automatic,"CARSOME PJ Automall, Selangor 14,748.1 km\n ...",Luxury,https://www.carsome.my/buy-car/bmw/x3/2022-bmw...
1835,2020,Perodua Myvi AV 1.5,"RM\n 46,600",RM 511,"83,531 km",Automatic,"CARSOME Showroom Kuantan Avenue, Pahang 14,612...",National Daily Drive,https://www.carsome.my/buy-car/perodua/myvi/20...

In [37]:
df['Model'].head()

0               Perodua Myvi SE 1.5
1    Subaru Forester L EyeSight 2.0
2           Honda Jazz S i-VTEC 1.5
3           Mazda CX-3 SKYACTIV 2.0
4               Perodua Myvi AV 1.5
Name: Model, dtype: object

In [38]:
df['Brand'] = df['Model'].str.split().str[0]

In [39]:
df['Brand'].head()

0    Perodua
1     Subaru
2      Honda
3      Mazda
4    Perodua
Name: Brand, dtype: object

In [40]:
df['Model'].head()

0               Perodua Myvi SE 1.5
1    Subaru Forester L EyeSight 2.0
2           Honda Jazz S i-VTEC 1.5
3           Mazda CX-3 SKYACTIV 2.0
4               Perodua Myvi AV 1.5
Name: Model, dtype: object

In [41]:
df['Model'] = df['Model'].str.split().str[1:].apply(lambda x: ' '.join(x))
df['Model'] = df['Model'].str.lower()

In [42]:
df['Model']

0                     myvi se 1.5
1         forester l eyesight 2.0
2               jazz s i-vtec 1.5
3               cx-3 skyactiv 2.0
4                     myvi av 1.5
                  ...
1831    a200 progressive line 1.3
1832        3 skyactiv-g high 2.0
1833                  vios gx 1.5
1834     x3 xdrive30i m sport 2.0
1835                  myvi av 1.5
Name: Model, Length: 1836, dtype: object

In [43]:
df['Total_Price'].head()

0     RM\n          35,400
1    RM\n          115,800
2     RM\n          52,900
3     RM\n          55,800
4     RM\n          49,900
Name: Total_Price, dtype: object

In [44]:
df['Total_Price'] = df['Total_Price'].str.replace(r'[^\d.]', '', regex=True).astype(float)
df.columns = df.columns.str.replace('Total_Price', 'Total_Price(RM)')

In [45]:
df['Total_Price(RM)'].head()

0     35400.0
1    115800.0
2     52900.0
3     55800.0
4     49900.0
Name: Total_Price(RM), dtype: float64

In [46]:
df['Mileage'].head()

0    92,189 km
1    14,200 km
2    75,759 km
3    59,833 km
4    69,974 km
Name: Mileage, dtype: object

In [47]:
df['Mileage'] = df['Mileage'].str.replace(r'km', '', regex=True)
df['Mileage'] = df['Mileage'].str.replace(',', '').astype(float)
df.columns = df.columns.str.replace('Mileage', 'Mileage(km)')

In [48]:
df['Mileage(km)'].head()

0    92189.0
1    14200.0
2    75759.0
3    59833.0
4    69974.0
Name: Mileage(km), dtype: float64

In [49]:
df['Transmission'].head()

0    Automatic
1    Automatic
2    Automatic
3    Automatic
4    Automatic
Name: Transmission, dtype: object

In [50]:
df['Transmission'] = df['Transmission'].str.replace('Manual', 'M')
df['Transmission'] = df['Transmission'].str.replace('Automatic', 'A')

In [51]:
df['Transmission']

0       A
1       A
2       A
3       A
4       A
       ..
1831    A
1832    A
1833    A
1834    A
1835    A
Name: Transmission, Length: 1836, dtype: object

In [52]:
df['Location'].head()

0    CARSOME Showroom Setia SPICE, Pulau Pinang 14,...
1    CARSOME PJ Automall, Selangor 14,748.1 km\n   ...
2    CARSOME Showroom Kuala Terengganu, Terengganu ...
3    CARSOME Showroom Kota Kinabalu, Sabah 13,814.5...
4    CARSOME Showroom Johor Jaya, Johor 14,832.8 km...
Name: Location, dtype: object

In [53]:
df['Location'] = df['Location'].str.lower()

In [54]:
df['Location']

0       carsome showroom setia spice, pulau pinang 14,...
1       carsome pj automall, selangor 14,748.1 km\n   ...
2       carsome showroom kuala terengganu, terengganu ...
3       carsome showroom kota kinabalu, sabah 13,814.5...
4       carsome showroom johor jaya, johor 14,832.8 km...
                              ...
1831    carsome showroom setiawangsa, kuala lumpur 14,...
1832    carsome showroom kempas, johor 14,839.0 km\n  ...
1833    carsome showroom setia spice, pulau pinang 14,...
1834    carsome pj automall, selangor 14,748.1 km\n   ...
1835    carsome showroom kuantan avenue, pahang 14,612...
Name: Location, Length: 1836, dtype: object

In [55]:
df['Highlight'].head()

0    National Daily Drive
1             Compact SUV
2             Daily Drive
3             Compact SUV
4    National Daily Drive
Name: Highlight, dtype: object

In [56]:
df['Highlight'] = df['Highlight'].str.replace(r'View 360', 'View 360°', regex=True)
df['Highlight'] = df['Highlight'].str.lower()

In [57]:
df['Highlight'].head()

0    national daily drive
1             compact suv
2             daily drive
3             compact suv
4    national daily drive
Name: Highlight, dtype: object

In [58]:
df['Price_per_month'].head()

0      RM 406
1    RM 1,137
2      RM 611
3      RM 711
4      RM 460
Name: Price_per_month, dtype: object

In [59]:
df['Price_per_month'] = df['Price_per_month'].str.replace(r'[^\d]', '', regex=True)
df['Price_per_month'] = df['Price_per_month'].str.replace(',', '').astype(float)
df.columns = df.columns.str.replace('Price_per_month', 'Price_per_month(RM)')

In [60]:
df['Price_per_month(RM)'].head()

0     406.0
1    1137.0
2     611.0
3     711.0
4     460.0
Name: Price_per_month(RM), dtype: float64

In [61]:
df.isnull().sum()

Year                   0
Model                  0
Total_Price(RM)        0
Price_per_month(RM)    0
Mileage(km)            0
Transmission           0
Location               1
Highlight              0
URL                    0
Brand                  0
dtype: int64

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1836 entries, 0 to 1835
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 1836 non-null   int64
 1   Model                1836 non-null   object
 2   Total_Price(RM)      1836 non-null   float64
 3   Price_per_month(RM)  1836 non-null   float64
 4   Mileage(km)          1836 non-null   float64
 5   Transmission         1836 non-null   object
 6   Location             1835 non-null   object
 7   Highlight            1836 non-null   object
 8   URL                  1836 non-null   object
 9   Brand                1836 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 143.6+ KB

In [63]:
df.dropna()

,Year,Model,Total_Price(RM),Price_per_month(RM),Mileage(km),Transmission,Location,Highlight,URL,Brand
0,2017,myvi se 1.5,35400.0,406.0,92189.0,A,"carsome showroom setia spice, pulau pinang 14,...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua
1,2023,forester l eyesight 2.0,115800.0,1137.0,14200.0,A,"carsome pj automall, selangor 14,748.1 km\n ...",compact suv,https://www.carsome.my/buy-car/subaru/forester...,Subaru
2,2018,jazz s i-vtec 1.5,52900.0,611.0,75759.0,A,"carsome showroom kuala terengganu, terengganu ...",daily drive,https://www.carsome.my/buy-car/honda/jazz/2018...,Honda
3,2016,cx-3 skyactiv 2.0,55800.0,711.0,59833.0,A,"carsome showroom kota kinabalu, sabah 13,814.5...",compact suv,https://www.carsome.my/buy-car/mazda/cx-3/2016...,Mazda
4,2021,myvi av 1.5,49900.0,460.0,69974.0,A,"carsome showroom johor jaya, johor 14,832.8 km...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua
...,...,...,...,...,...,...,...,...,...,...
1831,2019,a200 progressive line 1.3,132000.0,1447.0,30014.0,A,"carsome showroom setiawangsa, kuala lumpur 14,...",luxury,https://www.carsome.my/buy-car/mercedes-benz/a...,Mercedes-Benz
1832,2018,3 skyactiv-g high 2.0,69000.0,828.0,97077.0,A,"carsome showroom kempas, johor 14,839.0 km\n ...",upgrade daily drive,https://www.carsome.my/buy-car/mazda/3/2018-ma...,Mazda
1833,2016,vios gx 1.5,50500.0,686.0,144662.0,A,"carsome showroom setia spice, pulau pinang 14,...",daily drive,https://www.carsome.my/buy-car/toyota/vios/201...,Toyota
1834,2022,x3 xdrive30i m sport 2.0,219800.0,2409.0,47126.0,A,"carsome pj automall, selangor 14,748.1 km\n ...",luxury,https://www.carsome.my/buy-car/bmw/x3/2022-bmw...,BMW
1835,2020,myvi av 1.5,46600.0,511.0,83531.0,A,"carsome showroom kuantan avenue, pahang 14,612...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df.to_csv('carsome_data_cleaned.csv', index=False)
files.download('carsome_data_cleaned.csv')