In [14]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
df = pd.read_csv('../../data/proccesed/carsome_data_cleaned.csv')

In [3]:
df

,Year,Model,Total_Price(RM),Price_per_month(RM),Mileage(km),Transmission,Location,Highlight,URL,Brand
0,2017,myvi se 1.5,35400.0,406.0,92189.0,A,"carsome showroom setia spice, pulau pinang 14,...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua
1,2023,forester l eyesight 2.0,115800.0,1137.0,14200.0,A,"carsome pj automall, selangor 14,748.1 km\n ...",compact suv,https://www.carsome.my/buy-car/subaru/forester...,Subaru
2,2018,jazz s i-vtec 1.5,52900.0,611.0,75759.0,A,"carsome showroom kuala terengganu, terengganu ...",daily drive,https://www.carsome.my/buy-car/honda/jazz/2018...,Honda
3,2016,cx-3 skyactiv 2.0,55800.0,711.0,59833.0,A,"carsome showroom kota kinabalu, sabah 13,814.5...",compact suv,https://www.carsome.my/buy-car/mazda/cx-3/2016...,Mazda
4,2021,myvi av 1.5,49900.0,460.0,69974.0,A,"carsome showroom johor jaya, johor 14,832.8 km...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua
...,...,...,...,...,...,...,...,...,...,...
1831,2019,a200 progressive line 1.3,132000.0,1447.0,30014.0,A,"carsome showroom setiawangsa, kuala lumpur 14,...",luxury,https://www.carsome.my/buy-car/mercedes-benz/a...,Mercedes-Benz
1832,2018,3 skyactiv-g high 2.0,69000.0,828.0,97077.0,A,"carsome showroom kempas, johor 14,839.0 km\n ...",upgrade daily drive,https://www.carsome.my/buy-car/mazda/3/2018-ma...,Mazda
1833,2016,vios gx 1.5,50500.0,686.0,144662.0,A,"carsome showroom setia spice, pulau pinang 14,...",daily drive,https://www.carsome.my/buy-car/toyota/vios/201...,Toyota
1834,2022,x3 xdrive30i m sport 2.0,219800.0,2409.0,47126.0,A,"carsome pj automall, selangor 14,748.1 km\n ...",luxury,https://www.carsome.my/buy-car/bmw/x3/2022-bmw...,BMW
1835,2020,myvi av 1.5,46600.0,511.0,83531.0,A,"carsome showroom kuantan avenue, pahang 14,612...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua

In [7]:
numerical_col = df.select_dtypes(include=[np.number])
categorical_col = df.select_dtypes(exclude=[np.number])

In [8]:
def remove_outliers_iqr(df, columns):
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    return df

df = remove_outliers_iqr(df, numerical_col)

In [13]:
df

,Year,Model,Total_Price(RM),Price_per_month(RM),Mileage(km),Transmission,Location,Highlight,URL,Brand
0,2017,myvi se 1.5,35400.0,406.0,92189.0,A,"carsome showroom setia spice, pulau pinang 14,...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua
1,2023,forester l eyesight 2.0,115800.0,1137.0,14200.0,A,"carsome pj automall, selangor 14,748.1 km\n ...",compact suv,https://www.carsome.my/buy-car/subaru/forester...,Subaru
2,2018,jazz s i-vtec 1.5,52900.0,611.0,75759.0,A,"carsome showroom kuala terengganu, terengganu ...",daily drive,https://www.carsome.my/buy-car/honda/jazz/2018...,Honda
3,2016,cx-3 skyactiv 2.0,55800.0,711.0,59833.0,A,"carsome showroom kota kinabalu, sabah 13,814.5...",compact suv,https://www.carsome.my/buy-car/mazda/cx-3/2016...,Mazda
4,2021,myvi av 1.5,49900.0,460.0,69974.0,A,"carsome showroom johor jaya, johor 14,832.8 km...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua
...,...,...,...,...,...,...,...,...,...,...
1828,2017,vios trd sportivo 1.5,53600.0,715.0,36537.0,A,"carsome showroom kota kinabalu, sabah 13,814.5...",daily drive,https://www.carsome.my/buy-car/toyota/vios/201...,Toyota
1830,2020,c-hr 1.8,101800.0,1116.0,40220.0,A,"carsome pj automall, selangor 14,748.1 km\n ...",compact suv,https://www.carsome.my/buy-car/toyota/c-hr/202...,Toyota
1832,2018,3 skyactiv-g high 2.0,69000.0,828.0,97077.0,A,"carsome showroom kempas, johor 14,839.0 km\n ...",upgrade daily drive,https://www.carsome.my/buy-car/mazda/3/2018-ma...,Mazda
1833,2016,vios gx 1.5,50500.0,686.0,144662.0,A,"carsome showroom setia spice, pulau pinang 14,...",daily drive,https://www.carsome.my/buy-car/toyota/vios/201...,Toyota
1835,2020,myvi av 1.5,46600.0,511.0,83531.0,A,"carsome showroom kuantan avenue, pahang 14,612...",national daily drive,https://www.carsome.my/buy-car/perodua/myvi/20...,Perodua

In [ ]:
df.to_csv('carsome_data_super_cleaned.csv', index=False)
files.download('carsome_data_super_cleaned.csv')